#!/bin/bash -e
if [[ ! -f "/home/spark-3d4a1c77-df58-48c4-a2cf-1b/tmp/uv/uv_0.6.10_linux_amd64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-3d4a1c77-df58-48c4-a2cf-1b/tmp/uv/uv_0.6.10_linux_amd64" "$@"
